#!/bin/bash
set -e

## Apache Spark

\`\`\`
$(docker run --rm ${IMAGE_NAME} bash -c '$SPARK_HOME/bin/spark-submit --version' 2>&1)
\`\`\`


## R Packages

\`\`\`
$(docker run --rm ${IMAGE_NAME} R --version)
\`\`\`

\`\`\`
$(docker run --rm ${IMAGE_NAME} R --silent -e 'installed.packages(.Library)[, c(1,3)]')
\`\`\`
