language: generic

sudo: required

services:
    - docker

env:
  global:
    - CACHE_DIR=$HOME/.cache/docker

cache:
  directories:
    - $CACHE_DIR

before_install:
  - make layers-from-cache

script:
  - make build-test-all

before_cache:
  - make cached-layers

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then make tag-all retry/push-all; fi

