#!/bin/bash
# set permissions on a directory
# after any installation, if a directory needs to be (human) user-writable,
# run this script on it.
# It will make everything in the directory owned by the group $NB_OWNER_GROUP
# and writable by that group.
# Deployments that want to set a specific user id can preserve permissions
# by adding the `--group-add user-writable` line to `docker run`.

# uses find to avoid touching files that already have the right permissions,
# which would cause massive image explosion

# right permissions are:
# group=$NB_OWNER_GROUP
# AND permissions include group rwX (directory-execute)

set -e

for d in $@; do
  find "$d" \
    ! \( \
      -group $NB_OWNER_GROUP \
      -a -perm -g+rwX  \
    \) \
    -exec chgrp $NB_OWNER_GROUP {} \; \
    -exec chmod g+rwX {} \;
done
