name: "(maintainers only) Blank issue"
description: For maintainers only
labels: []

body:
  - type: markdown
    attributes:
      value: |
        This is a blank issue template for maintainers to use as needed.
