name: Bug report
description: Create a report to help us improve
labels: ["type:Bug"]

body:
  - type: markdown
    attributes:
      value: |
        Hi! Thanks for using the Jupyter Docker Stacks and taking some time to contribute to this project.

        We'd appreciate it if you could check out the [Troubleshooting common problems](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html) section in the documentation,
        as well as [existing issues](https://github.com/jupyter/docker-stacks/issues?q=is%3Aissue) prior to submitting an issue to avoid duplication.

        Please answer the following sections to help us troubleshoot the problem.

  - type: dropdown
    attributes:
      label: What docker image(s) are you using?
      description: Select as many images as applicable
      multiple: true
      options:
        - all-spark-notebook
        - base-notebook
        - datascience-notebook
        - docker-stacks-foundation
        - julia-notebook
        - minimal-notebook
        - pyspark-notebook
        - pytorch-notebook
        - r-notebook
        - scipy-notebook
        - tensorflow-notebook
    validations:
      required: true

  - type: input
    attributes:
      label: Host OS system
      placeholder: |
        Example:
        Ubuntu 22.04
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Host architecture
      options:
        - x86_64
        - aarch64
    validations:
      required: true

  - type: textarea
    attributes:
      label: What Docker command are you running?
      description: |
        What complete docker command do you run to launch the container (omitting sensitive values)?
      placeholder: |
        Example:
        `docker run -it --rm -p 8888:8888 quay.io/jupyter/base-notebook`
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to Reproduce the problem?
      description: Please provide steps to reproduce this bug (once the container is running).
      placeholder: |
        Example:

        1. Visit <http://localhost:8888>

        2. Start an R notebook

        3. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Command output
      render: bash session
      description: |
        Provide the output of the steps above, including the commands
        themselves and Docker's output/traceback etc. If you're familiar with
        Markdown, this block will have triple backticks added automatically
        around it -- you don't have to add them.

        If you want to present output from multiple commands, please present
        that as a shell session (commands you run get prefixed with `$ `).
        Please also ensure that the "How to reproduce" section contains matching
        instructions for reproducing this.

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
      placeholder: |
        Example: `ggplot` output appears in my notebook.

  - type: textarea
    attributes:
      label: Actual behavior
      description: |
        A clear and concise description of what the bug is.
      placeholder: |
        Example: No output is visible in the notebook and the Server log contains messages about ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Latest Docker version
      description: You should try to use the latest Docker version
      options:
        - label: I've updated my Docker version to the latest available, and the issue persists
          required: true
