name: Build environment
description: Create a build environment

runs:
  using: composite
  steps:
    - name: Set Up Python 🐍
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install Dev Dependencies 📦
      run: |
        pip install --upgrade pip
        pip install --upgrade -r requirements-dev.txt
      shell: bash

    - name: Set up Docker (missing on macOS) 🐳
      run: |
        brew install colima
        brew install --cask docker
        colima start
      shell: bash
      if: runner.os == 'macOS'
