name: Build environment
description: Create a build environment

runs:
  using: composite
  steps:
    - name: Set Up Python 🐍
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.12

    - name: Install Dev Dependencies 📦
      run: |
        pip install --upgrade pip
        pip install --upgrade -r requirements-dev.txt
      shell: bash

    # We need to have a recent docker version
    # More info: https://github.com/jupyter/docker-stacks/pull/2255
    # Can be removed after Docker Engine is updated
    # https://github.com/actions/runner-images/issues/11766
    - name: Set Up Docker 🐳
      uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 # v5.3.0
      with:
        set-host: true
