# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyter/tensorflow-notebook

MAINTAINER Jupyter Project <jupyter@googlegroups.com>

USER $NB_USER

# Install keras
RUN yes | pip -qq install keras
