name: "Free Disk Space (Ubuntu)"
description: "A GitHub Action to free up disk space on an Ubuntu GitHub Actions runner."

runs:
  using: "composite"
  steps:
    - name: Install cargo-binstall 📦
      uses: cargo-bins/cargo-binstall@75b4bfae1b2c753a6806bbce6e6cb89b602de33c # v1.22.0

    - name: Installing rmz
      shell: bash
      run: |
        cargo binstall -qy rmz
        ln -s ~/.cargo/bin/rmz /usr/local/bin/rmz

    - name: Freeing up disk space
      shell: bash
      run: |
        sudo rmz -f /usr/local/lib/android || true
        sudo rmz -f /usr/share/dotnet || true
        sudo rmz -f /opt/ghc /usr/local/.ghcup || true
        sudo rmz -f /usr/share/swift || true
        sudo rmz -f /usr/share/miniconda || true
        sudo rmz -f "${AGENT_TOOLSDIRECTORY}" || true
