name: Load Docker image
description: Download image artifact and load it to docker

inputs:
  image:
    description: Image name
    required: true
    type: string
  platform:
    description: Image platform
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Login to GHCR 🔐
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # dependabot updates to latest release
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull image from ghcr.io 📥
      run: |
        docker pull ghcr.io/jupyter/${{ inputs.image }}-${{ inputs.platform }}
        docker tag ghcr.io/jupyter/${{ inputs.image }}-${{ inputs.platform }} jupyter/${{ inputs.image }}
      shell: bash
