name: Load Docker image
description: Download image tar and load it to docker

inputs:
  image:
    description: Image name
    required: true
    type: string
  platform:
    description: Image platform
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download built image 📥
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.image }}-${{ inputs.platform }}
        path: /tmp/jupyter/images/
    - name: Load downloaded image to docker 📥
      run: |
        docker load --input /tmp/jupyter/images/${{ inputs.image }}-${{ inputs.platform }}.tar
        docker image ls --all
      shell: bash
    - name: Delete the file 🗑️
      run: rm /tmp/jupyter/images/${{ inputs.image }}-${{ inputs.platform }}.tar
      shell: bash
