name: Load Docker image
description: Download the image tar and load it to Docker

inputs:
  image:
    description: Image name
    required: true
  platform:
    description: Image platform
    required: true
  variant:
    description: Variant tag prefix
    required: true

runs:
  using: composite
  steps:
    - name: Download built image 📥
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: ${{ inputs.image }}-${{ inputs.platform }}-${{ inputs.variant }}
        path: /tmp/jupyter/images/

    - name: Load downloaded image to docker 📥
      run: |
        zstd \
          --uncompress \
          --stdout \
          --rm \
          /tmp/jupyter/images/${{ inputs.image }}-${{ inputs.platform }}-${{ inputs.variant }}.tar.zst \
          | docker load
      shell: bash

    - name: Show Docker images 📦
      run: docker image ls --all
      shell: bash
