name: Download build history lines and manifests from GitHub artifacts and push them to the GitHub wiki
# We're doing everything in one workflow on purpose
# This way we make sure we don't access wiki pages from several jobs simultaneously

env:
  PUSH_TO_REGISTRY: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' }}

on:
  workflow_call:

jobs:
  wiki-update:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    timeout-minutes: 1

    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Create dev environment 📦
        uses: ./.github/actions/create-dev-env

      - name: Compute commit hash tag 🏷
        id: hash
        run: echo "tag=${GITHUB_SHA::12}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Download all history lines 📥
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: "*-${{ steps.hash.outputs.tag }}.txt"
          path: /tmp/jupyter/hist_lines/
          merge-multiple: true

      - name: Download all manifests 📥
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: "*-${{ steps.hash.outputs.tag }}.md"
          path: /tmp/jupyter/manifests/
          merge-multiple: true

      - name: Checkout Wiki Repo 📃
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki_src/

      - name: Update wiki 🏷
        run: |
          python3 -m wiki.update_wiki \
            --wiki-dir wiki_src/ \
            --hist-lines-dir /tmp/jupyter/hist_lines/ \
            --manifests-dir /tmp/jupyter/manifests/ \
            --repository ${{ github.repository }}
        shell: bash

      - name: Push Wiki to GitHub 📤
        if: env.PUSH_TO_REGISTRY == 'true'
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "Automated wiki publish for ${{ github.sha }}"
          repository: wiki_src/
