name: Run pre-commit hooks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  run-hooks:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 5

    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set Up Python 🐍
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.12

      - name: Install pre-commit 📦
        run: |
          pip install --upgrade pip
          pip install --upgrade pre-commit

      - name: Run pre-commit hooks ✅
        run: pre-commit run --all-files --hook-stage manual
